version: '2.0'

services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: nodemon server.js
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - db
    environment:
      PORT: 3000