version: '2.0'

services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"

  web:
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000